data:
  train_dataset: /home/soroush1/projects/def-kohitij/soroush1/training_fast_publish_faster/data/imagenet_train_256.ffcv
  val_dataset: /home/soroush1/projects/def-kohitij/soroush1/training_fast_publish_faster/data/imagenet_validation_256.ffcv
  in_memory: 1
  num_workers: 40
dist:
  world_size: 4
logging:
  folder: ./vgg16_logs
  log_level: 1
lr:
  lr_schedule_type: steplr
  lr_step_size: 30
  lr_gamma: 0.1
  lr_warmup_epochs: 0
  lr_warmup_method: linear
  lr_warmup_decay: 0.01
  lr: 0.01
model:
  arch: vgg16
resolution:
  end_ramp: 13
  max_res: 192
  min_res: 160
  start_ramp: 11
  fix_res: 0
training:
  eval_only: 0
  batch_size: 128
  optimizer: sgd
  momentum: 0.9
  weight_decay: 0.0001
  epochs: 91
  label_smoothing: 0.1
  distributed: 1
  use_blurpool: 1
  bn_wd: 0
validation:
  batch_size: 512
  resolution: 256
  lr_tta: true